In [3]:
! pip install numpy

In [10]:
# 1D array using numpy
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(arr1, type(arr1))
print(arr1.shape) # (6,) means single dimention array.

[1 2 3 4 5 6] <class 'numpy.ndarray'>
(6,)


In [14]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6)
# 1,6 means 1 row and 6 columns 

array([[1, 2, 3, 4, 5, 6]])

In [15]:
# Think of shape like the “size and layout” of a box full of items.
# In numpy every array has a shape which tells, how many rows and columns it has . 
# it has 2 rows and three colmns. 

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.shape)  # Output: (2, 3)


(2, 3)


In [21]:
# Imagine you have a pile of 12 Lego bricks, and you want to arrange them into a rectangle or cube.The total number of bricks stays the same, but you can change how you arrange them.
# That’s exactly what reshape() does:
# It changes the layout of the array without changing the data.
a = np.array([1,2,3,4,5,6,7,8])
print(a)
a.reshape(2,4)








[1 2 3 4 5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
# When you're not sure about one of the dimensions, you can put -1, and NumPy will figure it out for you automatically.

arr3 = np.arange(12)
ans = arr3.reshape(2,-1)
print(ans)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [37]:
# I am not sure about rows but colomns are 2. 
arr3 = np.arange(14)
ans = arr3.reshape(-1,2)
print(ans)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]


In [36]:
arr3 = np.arange(6)
ans = arr3.reshape(3,-1)
print(ans)

[[0 1]
 [2 3]
 [4 5]]


In [39]:
# add list within a list 
arr = np.array([[1,2,3,4,5,6]])
print(arr)

[[1 2 3 4 5 6]]


In [50]:
# 2D ARRAY
arr = np.array([[1,2,3],[4,5,6], [1,2,3] ,[7,8,9]])
print(arr)
print(arr.shape)
print("Array Dimensions:", arr.ndim)


[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]]
(4, 3)
Array Dimensions: 2


In [58]:
# np.arange(start, stop, step)
arr = np.arange(0,10,2)
print(arr)

b = arr.reshape(1,5)
print(b)

arr.reshape(5,1)

[0 2 4 6 8]
[[0 2 4 6 8]]


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [60]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
# identity metrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [89]:
# Attributes of Numpy
arr= np.array([[1,2,3],[4,5,6],[7,8,9] , [10,11,12]])

print("print array: \n",arr , "\n")
print("Print Type: " , type(arr) , "\n")
print("print shape of array : ", arr.shape , "\n") #4 rows and three columns
print("print dimensions of array: ", arr.ndim , "\n")
print("print Data Type: " , arr.dtype , "\n")
print("Item size in bytes: " , arr.itemsize , "\n")


print array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

Print Type:  <class 'numpy.ndarray'> 

print shape of array :  (4, 3) 

print dimensions of array:  2 

print Data Type:  int64 

Item size in bytes:  8 



In [110]:
# Numpy Vectorized operation
v1 = np.array([1,2,3,4,5])
v2 = np.array([10,20,30,40,50])
print(f"First array {v1} \nSecond array {v2}")
v3 = v1+v2
print(f"Addition : {v1} + {v2} = {v3}")
v3 = v1-v2
print(f"Subtraction : {v1} - {v2} ={v3}")
v3 = v1*v2
print(f"Multiplication : {v1} * {v2} = {v3} ")
print("Division :" ,v1/v2)



First array [1 2 3 4 5] 
Second array [10 20 30 40 50]
Addition : [1 2 3 4 5] + [10 20 30 40 50] = [11 22 33 44 55]
Subtraction : [1 2 3 4 5] - [10 20 30 40 50] =[ -9 -18 -27 -36 -45]
Multiplication : [1 2 3 4 5] * [10 20 30 40 50] = [ 10  40  90 160 250] 
Division : [0.1 0.1 0.1 0.1 0.1]


In [114]:
# Universal functions:
# Functions applies to entire array
arr = np. array([4,16,9,144])
print(np.sqrt(arr))

# Exponential 
print(np.exp(arr))

# sine 
print(np.sin(arr))

# log
print(np.log(arr))

[ 2.  4.  3. 12.]
[5.45981500e+01 8.88611052e+06 8.10308393e+03 3.45466066e+62]
[-0.7568025  -0.28790332  0.41211849 -0.49102159]
[1.38629436 2.77258872 2.19722458 4.9698133 ]


In [115]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [116]:
# indending in array:
print(arr[0])

[1 2 3 4]


In [119]:
print(arr[0,0]) # 0 row 0 column
print(arr[0,1]) # 0 row 1 column

1
2


In [120]:
# print 5 to 12 means 2 and 3 row 
print(arr[1:])


[[ 5  6  7  8]
 [ 9 10 11 12]]


In [121]:
# print last row
print(arr[-1:])

[[ 9 10 11 12]]


In [126]:
print(arr)
print("index")
print(arr[1:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
index
[[ 7  8]
 [11 12]]


In [130]:
# entire 1 row from index 1 to end  and 1 column 
print(arr[1:,1])

# entire 1 row from index 0 to end  and 1 column 
print("\no row till end ")
print(arr[0:,1])

[ 6 10]

o row till end 
[ 2  6 10]


In [131]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [132]:
# This is 2D slicing, where the syntax is arr[row_slice, column_slice]
# 0:2 → select rows from index 0 up to (but not including) 2 → i.e., row 0 and row 1
# 1: → select columns starting from index 1 to the end

arr[0:2, 1:]




array([[2, 3, 4],
       [6, 7, 8]])

In [133]:

arr[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [134]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [135]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [137]:
# from row index 1 to end  1:
# from column index 1 to 3 but it doesn't include 3.
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [138]:
# modify array
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [139]:
arr[1:] = 300
print(arr)

[[100   2   3   4]
 [300 300 300 300]
 [300 300 300 300]]


In [144]:
# statistical concepts --Normalization 
data = np.array([1,2,3,4,5])
# calculate mean and standard deviation 

mean1 = np.mean(data)
std_dev = np.std(data)

# Normalize the data:
normalize_data = (data - mean1) /std_dev
print("Normalized data: ",normalize_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [152]:
# statstical Operation:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median 
median = np.median(data)
print("Median: ", median)

# standard Derivation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ", variance)


Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [155]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data > 5



array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [156]:
# retrive the elements greater than 5

data[data>5]

array([ 6,  7,  8,  9, 10])

In [161]:
data[(data>=5) & (data<=8)]


array([5, 6, 7, 8])